---
title: "My-first-post"
date: 2018-05-04
---
title: This is my awesome Title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Woah. This is a description.

# social links
twitter_username: your-twitter-handle
github_username:  anettpozsar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: to minima
